### ISSUE TITLE
Class info Screen

### ISSUE THREAD

**Issue by tbhall** [SCCapstone/AdviseMe#127]

**Comment by tbhall** [comment]
It's not completely done

**Comment by tbhall** [comment]
Class info screen created

**Comment by parsonsbatsc** [comment]
There's a minor typo with Departments, where one class has the course number and department listed under "departments."  This could be fixed by validating departments.

Is this supposed to correspond to the courses the student is planning to take, or the courses the student has taken and is taking?

**Comment by tbhall** [comment]
@parsonsbatsc If you could submit a picture and the process as to the bug that you came across that would be most helpful and appreciated.

Thanks,
AdviseMe team

**Comment by parsonsbatsc** [comment]
It was just sorting classes by department that showed me the bug.  It looks like the Course Number was appended to the Department.  It was probably just a typo when it was entered, but you could add some simple validation to not allow numbers in the department field.

![strangedepartment](https://user-images.githubusercontent.com/2502109/37004667-32c94448-209f-11e8-9d24-b6e47aca42cb.jpg)

**Comment by tbhall** [comment]
@parsonsbatsc Thanks for that catch.
