### ISSUE TITLE
Edit classes screen

### ISSUE THREAD

**Issue by tbhall** [SCCapstone/AdviseMe#128]

**Comment by parsonsbatsc** [comment]
Editing and deleting appear to function properly.  Adding a class simply added a blank line.

**Comment by tbhall** [comment]
@parsonsbatsc So how the smart tables work is that you click the add button a new item drops and you are able to add the information into the new items blank fields. Then when you have the information that you need in there you click the check mark and boom, You got yourself a new class

**Comment by parsonsbatsc** [comment]
I tried that yesterday, and it didn't add the class.  I'll try it again today.  This all might be the same issue - communication with the database.  It might just not be updating the table after the class is added.  I'll try it again today to double-check.

It did allow me to add the class the way you said.  It just didn't update the list of classes afterwards.  I could only get as far as the blank line.  I could edit the ones that were already in the database, but the new one didn't stay.  I'll try it again (along with the other "add" problems) in case it was an internet hiccup.

**Comment by josemvidal** [comment]
Yeah, layout is confusing. If things are next to each other, people will assume they are related. It is one of the Design Principles I covered in [my lecture on Design Principles](https://cse.sc.edu/capstone/lecture/design)

![advise me 2018-03-06 17-21-59](https://user-images.githubusercontent.com/228704/37061974-22f3e248-2163-11e8-9be8-6129da108631.png)
