### ISSUE TITLE
Edit students

### ISSUE THREAD

**Issue by tbhall** [SCCapstone/AdviseMe#129]

**Comment by parsonsbatsc** [comment]
Editing students works properly.  Adding them doesn't seem to be implemented yet.

**Comment by tbhall** [comment]
@parsonsbatsc Actually if you login as admin you can see that under administration you go to edit permissions (probably needs to be labeled something different) you are able to add a user there

**Comment by parsonsbatsc** [comment]
I tried that when I was logged in as an admin, and wasn't able to add a user.  This might be the same issue as the other database additions with it just not updating the page yet.

**Comment by tmoon8730** [comment]
@parsonsbatsc You are correct that feature is not implemented yet. It is now referenced in #192 .

@tbhall I believe you are looking at a different thing.

**Comment by parsonsbatsc** [comment]
@tmoon8730 Thanks for letting me know.  Otherwise I probably would have been wondering if my internet access was being flaky again.
