### ISSUE TITLE
The user will be able to access and view (CS and CE) course catalog

### ISSUE THREAD

**Issue by Alcamech** [SCCapstone/AdviseMe#13]
The user will be able to access and view (CS and CE with Carolina Core) course catalog for the university and course info, including:   
   - a. Course description.
   - b. Course prerequisites.
   - c. Course semester offerings.
   - d. Course instructor and offered times.

**Comment by josemvidal** [comment]
All we can see now are: Dept, course number, course title. Correct?


<img width="1350" alt="advise_me" src="https://user-images.githubusercontent.com/228704/33804819-eb10771e-dd7a-11e7-99ef-73082cf3267e.png">

**Comment by dvjr22** [comment]
That is all we are displaying at the moment, but there is more info in the db.
