### ISSUE TITLE
Class info that needs to be added to DB if possible

### ISSUE THREAD

**Issue by ethangamma24** [SCCapstone/AdviseMe#145]
- [x] Semester Offered
- [x] Required grade for pre-reqs
- [x] Credit hours
- [x] Course description
- [x] Related classes (might not be needed)

**Comment by dvjr22** [comment]
Course description is general as of now and won't be added for specific classes.

**Comment by dvjr22** [comment]
Credit hrs are already in the latest build of the db.

**Comment by dvjr22** [comment]
Hall and I discussed issues about related classes, and they won't be added. Prereqs are in the db, if those are needed.

**Comment by dvjr22** [comment]
Semester offered won't be added either, as it is too specific for our current build.

**Comment by dvjr22** [comment]
Required grade depend on major.  Exploring how best to incorporate this into the db.
