### ISSUE TITLE
Show Beta to Freshmen Advisors at Student Services

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/AdviseMe#153]
Get some feedback. Cut-n-paste the feedback here and then close this.

I think it will help you a lot to get some feedback from people who might actually use your app, who are not you.

**Comment by dvjr22** [comment]
Thanks!                                   Sent from my BlackBerry KEYOne    From: notifications@github.comSent: February 28, 2018 8:51 AMTo: AdviseMe@noreply.github.comReply-to: reply@reply.github.comCc: dvjr22@gmail.com; assign@noreply.github.comSubject: Re: [SCCapstone/AdviseMe] Show Beta to Freshmen Advisors at Student Services (#153)Assigned #153 to @dvjr22.

**Comment by tbhall** [comment]
@josemvidal Would you happen to have the emails of the Freshmen advisors?

**Comment by josemvidal** [comment]
Here https://www.sc.edu/study/colleges_schools/engineering_and_computing/supportservices/firstyearadvising.php

**Comment by tbhall** [comment]
So far, I like the look of it, but...
--I was confused by what a Class Request is.
--I didn't see how to add your current/completed courses.

Brian McCaster

**Comment by tmoon8730** [comment]
@tbhall can this issue be closed now? Did you take the feedback and make issues out of it?
