### ISSUE TITLE
SSL Encryption

### ISSUE THREAD

**Issue by tbhall** [SCCapstone/AdviseMe#173]

**Comment by tmoon8730** [comment]
The validation request is pending and we should have SSL later today.

**Comment by tbhall** [comment]
@tmoon8730 Can this issue be closed?

**Comment by tmoon8730** [comment]
Apparently, SSL is more complicated than I originally thought @tbhall and our AWS issued certs cannot be used in an EC2 server only in Elastic Beanstalk. 

Looking into other SSL options.

**Comment by tmoon8730** [comment]
https://www.theadviseme.com is now SSL secured
