### ISSUE TITLE
Advisor Check screen 

### ISSUE THREAD

**Issue by tbhall** [SCCapstone/AdviseMe#178]
This is the screen that the advisor sees all of his students submissions (He can see those he has checked off and those he has to check)

**Comment by ethangamma24** [comment]
@dvjr22 we might need to make a change to the DB to get this done. Should be as simple as adding a couple of booleans into the cart collection: one to reflect if the student has submitted the cart for approval, one to reflect if the advisor approves it or not, and one to reflect if the advisor has reviewed it.
