### ISSUE TITLE
DevTools failed to parse SourceMap:

### ISSUE THREAD

**Issue by tbhall** [SCCapstone/AdviseMe#205]
New warning I get when running the project locally. Could be from the removal of package

**Comment by tmoon8730** [comment]
For sure from a removal of a package. Not sure which package though....

**Comment by tmoon8730** [comment]
@tbhall I looked into this and as far as I can tell its just a warning from Chrome and shouldn't cause any issues. Going to close the issue but if it causes problems in the future we can reopen then with more details.
