### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by KMCGamer** [SCCapstone/AdviseMe#94]
👌👀👌👀👌👀👌👀👌👀 good repo gooԁ RepO👌 thats ✔ some good👌👌**commits** right👌👌there👌👌👌 right✔there ✔✔if i do saү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) _mMMMMᎷМ_💯 👌👌 👌**НO0ОଠO**OOO_OОଠଠOoooᵒᵒ_ᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good rEPO!

![](https://i.imgur.com/wvlVzH2.gif)

**Comment by tbhall** [comment]
@KMCGamer ,
Not a real issue, but thank you for your support! We accept donations in venmo to tbhall. We also accept ideas for the future of this project and hope that you keep this repo in your starred repos!!
Sincerely,
Captin Hall
